import { MonsterData, Relic, SpecialOrbInfo, ChallengeModifier } from '../types';

export const ORB_PHYSICS = {
  // 空間與視口
  VIRTUAL_WIDTH: 720,
  VIRTUAL_HEIGHT: 1280,
  WALL_LEFT: 24,
  WALL_RIGHT: 696,
  CEILING_TOP: 140,
  FLOOR_DEAD_ZONE: 1260,

  // 發射台位置
  CANNON_X: 360,
  CANNON_Y: 155,

  // 彈珠 (Mana Orb) 運動學
  ORB_RADIUS: 10,
  ORB_MASS: 1.0,
  GRAVITY_Y: 980,
  AIR_DRAG: 0.9992,
  TERMINAL_VELOCITY: 1600,
  LAUNCH_SPEED: 950,

  // 釘子 (Pegs) 與機關幾何
  PEG_RADIUS: 9,
  PEG_RESTITUTION: 0.78,
  MUSHROOM_RADIUS: 24,
  MUSHROOM_RESTITUTION: 1.65,
  TNT_RADIUS: 18,
  TNT_BLAST_RADIUS: 85,
  PORTAL_RADIUS: 22,
  PORTAL_EXIT_BOOST: 1.15,
  SHIELD_CORE_RADIUS: 14,
  MINION_PEG_RADIUS: 12,

  // 集球桶 (Bucket)
  BUCKET_WIDTH: 130,
  BUCKET_HEIGHT: 38,
  BUCKET_Y: 1200,
  BUCKET_SPEED: 140,

  // 街機手感容錯與防卡死
  TRAJECTORY_MAX_STEPS: 260,
  TRAJECTORY_MAX_BOUNCES: 3,
  STUCK_VELOCITY_THRESHOLD: 25,
  STUCK_TIMEOUT_SECONDS: 2.2,
  HARD_TIMEOUT_SECONDS: 25.0,
};

export const COMBO_LADDER = [
  { minHits: 1, maxHits: 4, multiplier: 1.0, label: 'CASCADE', color: '#00f3ff' },
  { minHits: 5, maxHits: 9, multiplier: 1.25, label: 'HARMONY', color: '#00ff88' },
  { minHits: 10, maxHits: 17, multiplier: 1.6, label: 'RESONANCE', color: '#ffd700' },
  { minHits: 18, maxHits: 27, multiplier: 2.2, label: 'OVERDRIVE', color: '#bd00ff' },
  { minHits: 28, maxHits: 39, multiplier: 3.2, label: 'FRENZY!', color: '#ff0055' },
  { minHits: 40, maxHits: 9999, multiplier: 5.0, label: 'HYPER CASCADE!', color: '#ffeb3b' },
];

export const SPECIAL_ORBS_CONFIG: readonly SpecialOrbInfo[] = [
  {
    type: 'STANDARD',
    name: '奧術魔彈',
    subtitle: 'Standard Orb',
    description: '純粹奧術能量鑄造，具備均衡的反彈物理與速度。',
    icon: '🔮',
    color: '#00f3ff',
    glowColor: '#38bdf8',
  },
  {
    type: 'FROST',
    name: '寒霜晶球',
    subtitle: 'Frost Orb',
    description: '撞擊釘子附加冰凍易傷，下一次撞擊傷害高達 250%！',
    icon: '❄️',
    color: '#7dd3fc',
    glowColor: '#38bdf8',
  },
  {
    type: 'LIGHTNING',
    name: '混沌雷球',
    subtitle: 'Lightning Orb',
    description: '每次彈跳在空中隨機跳躍電弧穿透 2 顆遠處釘子。',
    icon: '⚡',
    color: '#facc15',
    glowColor: '#eab308',
  },
  {
    type: 'VOID',
    name: '虛空黑球',
    subtitle: 'Void Orb',
    description: '自帶重力扭曲光環，掠過釘子時直接吸附偏轉彈道。',
    icon: '🌀',
    color: '#c084fc',
    glowColor: '#a855f7',
  },
];

export const CHALLENGE_MODIFIERS: readonly ChallengeModifier[] = [
  {
    id: 'CHAOS_STORM',
    name: '混沌風暴',
    description: '彈珠重力微增，空中偶發隨機側向擾動力場，得分加成 +30%',
    icon: '🌪️',
    scoreBonusMultiplier: 1.3,
  },
  {
    id: 'HARDENED_PEGS',
    name: '釘刺硬化',
    description: '怪物每層額外生成 1 顆能量護盾核心釘，得分加成 +40%',
    icon: '🛡️',
    scoreBonusMultiplier: 1.4,
  },
  {
    id: 'FRENZY_PACE',
    name: '首領狂亂',
    description: '全場怪物攻擊倒數 -1 回合，但 Combo 連鎖分數倍率 +50%',
    icon: '🔥',
    scoreBonusMultiplier: 1.5,
  },
];

export const MONSTERS_CONFIG: readonly Omit<MonsterData, 'currentHp' | 'currentCountdown' | 'shieldCurrent' | 'isEnraged'>[] = [
  {
    floor: 1,
    name: '幽林史萊姆',
    title: 'Forest Slime',
    maxHp: 600,
    attackInterval: 4,
    attackDamage: 12,
    isBoss: false,
    specialSkillName: '黏液撞擊',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 2,
    name: '樹精守衛',
    title: 'Treant Guardian',
    maxHp: 950,
    attackInterval: 4,
    attackDamage: 15,
    isBoss: false,
    specialSkillName: '根鬚鞭笞',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 3,
    name: '劇毒巨蛛',
    title: 'Toxic Arachnid',
    maxHp: 1500,
    attackInterval: 3,
    attackDamage: 20,
    isBoss: false,
    specialSkillName: '致命毒刺',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 4,
    name: '狂暴石像鬼',
    title: 'Frenzied Gargoyle',
    maxHp: 2200,
    attackInterval: 3,
    attackDamage: 25,
    isBoss: false,
    specialSkillName: '碎岩重擊',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 5,
    name: '地穴熔岩巨魔',
    title: 'Magma Troll (BOSS)',
    maxHp: 3800,
    attackInterval: 3,
    attackDamage: 32,
    isBoss: true,
    specialSkillName: '熔岩烈焰護盾',
    hasShield: true,
    shieldMax: 3,
    minionCooldown: 2,
  },
  {
    floor: 6,
    name: '幻影刺客',
    title: 'Phantom Slayer',
    maxHp: 4400,
    attackInterval: 2,
    attackDamage: 28,
    isBoss: false,
    specialSkillName: '暗影突襲',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 7,
    name: '寒冰核心元素',
    title: 'Frost Core Elemental',
    maxHp: 5600,
    attackInterval: 3,
    attackDamage: 30,
    isBoss: false,
    specialSkillName: '冰晶穿刺',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 8,
    name: '遠古符文魔像',
    title: 'Ancient Rune Golem',
    maxHp: 7500,
    attackInterval: 3,
    attackDamage: 35,
    isBoss: false,
    specialSkillName: '符文防壁重錘',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 9,
    name: '深淵死靈術士',
    title: 'Abyssal Lich',
    maxHp: 9800,
    attackInterval: 2,
    attackDamage: 40,
    isBoss: false,
    specialSkillName: '亡魂暗黑收割',
    hasShield: false,
    shieldMax: 0,
    minionCooldown: 0,
  },
  {
    floor: 10,
    name: '混沌虛空古龍',
    title: 'Chaos Void Dragon (FINAL BOSS)',
    maxHp: 15000,
    attackInterval: 2,
    attackDamage: 50,
    isBoss: true,
    specialSkillName: '虛空天幕護盾 & 召喚虛空眼',
    hasShield: true,
    shieldMax: 4,
    minionCooldown: 2,
  },
];

export const ALL_RELICS: readonly Relic[] = [
  // 基礎遺物
  {
    id: 'split-core',
    name: '分裂核心',
    description: '單回合撞擊達 10 顆釘子時，分裂出 1 顆次級子球助戰。',
    icon: '🔮',
    iconColor: '#00f3ff',
    rarity: 'COMMON',
  },
  {
    id: 'singularity',
    name: '引力黑洞',
    description: '撞擊達 7 次時產生黑洞，牽引彈珠撞擊鄰近釘子。',
    icon: '🌀',
    iconColor: '#a855f7',
    rarity: 'RARE',
  },
  {
    id: 'chain-zap',
    name: '雷霆連鎖',
    description: '擊中弱點釘時，引發 3 道連鎖閃電引爆鄰近未被擊中的釘子。',
    icon: '⚡',
    iconColor: '#ffd700',
    rarity: 'EPIC',
  },
  {
    id: 'blast-resonance',
    name: '爆破諧振',
    description: 'TNT 爆炸半徑 +40%，傷害提升 +60%。',
    icon: '💥',
    iconColor: '#ff4400',
    rarity: 'COMMON',
  },
  {
    id: 'super-gum',
    name: '彈力橡膠',
    description: '彈性恢復係數提升至 0.88，彈珠滯空時間顯著增加。',
    icon: '🫧',
    iconColor: '#ff66cc',
    rarity: 'COMMON',
  },
  {
    id: 'piercing-spear',
    name: '穿透之矛',
    description: '發射後前 2 次撞擊可直接穿透釘子不反彈。',
    icon: '🗡️',
    iconColor: '#00ffcc',
    rarity: 'RARE',
  },
  {
    id: 'frost-nova',
    name: '霜凍新星',
    description: '單回合 Combo 突破 20 次時，使怪物下一次攻擊倒數 +1。',
    icon: '❄️',
    iconColor: '#38bdf8',
    rarity: 'RARE',
  },
  {
    id: 'soul-siphon',
    name: '靈魂汲取',
    description: '單回合每擊中 8 顆釘子，為玩家回復 1 點生命值。',
    icon: '💚',
    iconColor: '#4ade80',
    rarity: 'COMMON',
  },
  {
    id: 'midas-touch',
    name: '點金魔手',
    description: '彈珠掉入集球桶時，該回合總傷害額外 +30% 暴擊加成。',
    icon: '👑',
    iconColor: '#facc15',
    rarity: 'LEGENDARY',
  },
  {
    id: 'gravity-funnel',
    name: '引力導流',
    description: '集球桶寬度擴展 +35% (130px -> 175px)，大幅提升接球率。',
    icon: '🪣',
    iconColor: '#2dd4bf',
    rarity: 'COMMON',
  },
  {
    id: 'tuning-fork',
    name: '共鳴音叉',
    description: 'Combo 音階倍率增長速度提升 40%，更易觸發 5.0x 上限。',
    icon: '🎵',
    iconColor: '#ec4899',
    rarity: 'EPIC',
  },
  {
    id: 'twin-orbs',
    name: '雙重魔彈',
    description: '每次拉桿發射時，砲台間隔 80ms 連續發射 2 顆彈珠！',
    icon: '✨',
    iconColor: '#f59e0b',
    rarity: 'LEGENDARY',
  },

  // v1.1.0 協同遺物
  {
    id: 'overcharge-battery',
    name: '過載電池',
    description: '每次穿透或彈跳魔菇時，蓄積超導電能，使下一次彈跳傷害翻倍 (2.0x)！',
    icon: '🔋',
    iconColor: '#22c55e',
    rarity: 'EPIC',
  },
  {
    id: 'vampire-fang',
    name: '吸血尖牙',
    description: '每累計觸發 15 次釘子碰撞，立即為玩家恢復 1 點魔能 (Mana Orb)！',
    icon: '🧛',
    iconColor: '#f43f5e',
    rarity: 'EPIC',
  },
  {
    id: 'prism-splinter',
    name: '稜鏡碎屑',
    description: '彈珠撞擊 TNT 爆炸時，朝兩側額外分裂出 2 顆微型爆破子彈！',
    icon: '💎',
    iconColor: '#06b6d4',
    rarity: 'RARE',
  },
  {
    id: 'meteor-strike',
    name: '隕石衝擊',
    description: '彈珠穿過傳送門出口時產生全螢幕震波，引爆周遭 140px 內所有釘子！',
    icon: '☄️',
    iconColor: '#f97316',
    rarity: 'LEGENDARY',
  },
];
